---
abstract: 'SMS::Send driver for the Facilita Movel SMS service'
author:
  - 'Mario Celso Teixeira <marioct37@gmail.com>'
build_requires:
  Carp: '0'
  English: '0'
  HTTP::Tiny: '0'
  SMS::Send: '0'
  Test::More: '0'
  URI::Escape: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.31'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SMS-Send-BR-Facilitamovel
no_index:
  directory:
    - t
    - inc
requires:
  SMS::Send::Driver: '0'
resources:
  repository: https://github.com/marioct/SMS-Send-BR-Facilitamovel.git
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
